/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SPIFFS_ASSETS_FILES           3
#define MMAP_SPIFFS_ASSETS_CHECKSUM        0xAAB6
#define MMAP_SPIFFS_ASSETS_OFFSET          0x7E4C0

enum MMAP_SPIFFS_ASSETS_LISTS {
    MMAP_SPIFFS_ASSETS_APPEND_FILE_BIN = 0,        /*!< append_file.bin */
    MMAP_SPIFFS_ASSETS_FONT_20_BIN = 1,        /*!< font_20.bin */
    MMAP_SPIFFS_ASSETS_FONT_20_ALL_BIN = 2,        /*!< font_20_all.bin */
};
